### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by arsham** [arsham/logpipe#21]
Accept a configuration file for constructing the application and writiers.

```yaml
app:
  log_level: info
writers:
  elasticsearch:
     url: http://localhost:9200
     index: logs
  file:
     path: /var/log/logpipe/logs.log
```
